// Code generated by protoc-gen-go. DO NOT EDIT.
// source: skplug.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventType int32

const (
	EventType_CREATE EventType = 0
	EventType_UPDATE EventType = 1
	EventType_DELETE EventType = 2
)

var EventType_name = map[int32]string{
	0: "CREATE",
	1: "UPDATE",
	2: "DELETE",
}

var EventType_value = map[string]int32{
	"CREATE": 0,
	"UPDATE": 1,
	"DELETE": 2,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}

func (EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a95933fe5266f40f, []int{0}
}

type MetricType int32

const (
	MetricType_CPU_MILLIS                 MetricType = 0
	MetricType_CONCURRENT_REQUESTS_MILLIS MetricType = 1
)

var MetricType_name = map[int32]string{
	0: "CPU_MILLIS",
	1: "CONCURRENT_REQUESTS_MILLIS",
}

var MetricType_value = map[string]int32{
	"CPU_MILLIS":                 0,
	"CONCURRENT_REQUESTS_MILLIS": 1,
}

func (x MetricType) String() string {
	return proto.EnumName(MetricType_name, int32(x))
}

func (MetricType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a95933fe5266f40f, []int{1}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_a95933fe5266f40f, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Autoscaler struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Yaml                 string   `protobuf:"bytes,2,opt,name=yaml,proto3" json:"yaml,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Autoscaler) Reset()         { *m = Autoscaler{} }
func (m *Autoscaler) String() string { return proto.CompactTextString(m) }
func (*Autoscaler) ProtoMessage()    {}
func (*Autoscaler) Descriptor() ([]byte, []int) {
	return fileDescriptor_a95933fe5266f40f, []int{1}
}

func (m *Autoscaler) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Autoscaler.Unmarshal(m, b)
}
func (m *Autoscaler) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Autoscaler.Marshal(b, m, deterministic)
}
func (m *Autoscaler) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Autoscaler.Merge(m, src)
}
func (m *Autoscaler) XXX_Size() int {
	return xxx_messageInfo_Autoscaler.Size(m)
}
func (m *Autoscaler) XXX_DiscardUnknown() {
	xxx_messageInfo_Autoscaler.DiscardUnknown(m)
}

var xxx_messageInfo_Autoscaler proto.InternalMessageInfo

func (m *Autoscaler) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Autoscaler) GetYaml() string {
	if m != nil {
		return m.Yaml
	}
	return ""
}

type Pod struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	State                string   `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	LastTransition       int64    `protobuf:"varint,3,opt,name=last_transition,json=lastTransition,proto3" json:"last_transition,omitempty"`
	CpuRequest           int32    `protobuf:"varint,4,opt,name=cpu_request,json=cpuRequest,proto3" json:"cpu_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pod) Reset()         { *m = Pod{} }
func (m *Pod) String() string { return proto.CompactTextString(m) }
func (*Pod) ProtoMessage()    {}
func (*Pod) Descriptor() ([]byte, []int) {
	return fileDescriptor_a95933fe5266f40f, []int{2}
}

func (m *Pod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pod.Unmarshal(m, b)
}
func (m *Pod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pod.Marshal(b, m, deterministic)
}
func (m *Pod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pod.Merge(m, src)
}
func (m *Pod) XXX_Size() int {
	return xxx_messageInfo_Pod.Size(m)
}
func (m *Pod) XXX_DiscardUnknown() {
	xxx_messageInfo_Pod.DiscardUnknown(m)
}

var xxx_messageInfo_Pod proto.InternalMessageInfo

func (m *Pod) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Pod) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Pod) GetLastTransition() int64 {
	if m != nil {
		return m.LastTransition
	}
	return 0
}

func (m *Pod) GetCpuRequest() int32 {
	if m != nil {
		return m.CpuRequest
	}
	return 0
}

type EventRequest struct {
	Partition string    `protobuf:"bytes,1,opt,name=partition,proto3" json:"partition,omitempty"`
	Time      int64     `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Type      EventType `protobuf:"varint,3,opt,name=type,proto3,enum=proto.EventType" json:"type,omitempty"`
	// Types that are valid to be assigned to ObjectOneof:
	//	*EventRequest_Autoscaler
	//	*EventRequest_Pod
	ObjectOneof          isEventRequest_ObjectOneof `protobuf_oneof:"object_oneof"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *EventRequest) Reset()         { *m = EventRequest{} }
func (m *EventRequest) String() string { return proto.CompactTextString(m) }
func (*EventRequest) ProtoMessage()    {}
func (*EventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a95933fe5266f40f, []int{3}
}

func (m *EventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventRequest.Unmarshal(m, b)
}
func (m *EventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventRequest.Marshal(b, m, deterministic)
}
func (m *EventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventRequest.Merge(m, src)
}
func (m *EventRequest) XXX_Size() int {
	return xxx_messageInfo_EventRequest.Size(m)
}
func (m *EventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventRequest proto.InternalMessageInfo

func (m *EventRequest) GetPartition() string {
	if m != nil {
		return m.Partition
	}
	return ""
}

func (m *EventRequest) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *EventRequest) GetType() EventType {
	if m != nil {
		return m.Type
	}
	return EventType_CREATE
}

type isEventRequest_ObjectOneof interface {
	isEventRequest_ObjectOneof()
}

type EventRequest_Autoscaler struct {
	Autoscaler *Autoscaler `protobuf:"bytes,4,opt,name=autoscaler,proto3,oneof"`
}

type EventRequest_Pod struct {
	Pod *Pod `protobuf:"bytes,5,opt,name=pod,proto3,oneof"`
}

func (*EventRequest_Autoscaler) isEventRequest_ObjectOneof() {}

func (*EventRequest_Pod) isEventRequest_ObjectOneof() {}

func (m *EventRequest) GetObjectOneof() isEventRequest_ObjectOneof {
	if m != nil {
		return m.ObjectOneof
	}
	return nil
}

func (m *EventRequest) GetAutoscaler() *Autoscaler {
	if x, ok := m.GetObjectOneof().(*EventRequest_Autoscaler); ok {
		return x.Autoscaler
	}
	return nil
}

func (m *EventRequest) GetPod() *Pod {
	if x, ok := m.GetObjectOneof().(*EventRequest_Pod); ok {
		return x.Pod
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*EventRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*EventRequest_Autoscaler)(nil),
		(*EventRequest_Pod)(nil),
	}
}

type Stat struct {
	Time                 int64      `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	PodName              string     `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Type                 MetricType `protobuf:"varint,3,opt,name=type,proto3,enum=proto.MetricType" json:"type,omitempty"`
	Value                int32      `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Stat) Reset()         { *m = Stat{} }
func (m *Stat) String() string { return proto.CompactTextString(m) }
func (*Stat) ProtoMessage()    {}
func (*Stat) Descriptor() ([]byte, []int) {
	return fileDescriptor_a95933fe5266f40f, []int{4}
}

func (m *Stat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stat.Unmarshal(m, b)
}
func (m *Stat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stat.Marshal(b, m, deterministic)
}
func (m *Stat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stat.Merge(m, src)
}
func (m *Stat) XXX_Size() int {
	return xxx_messageInfo_Stat.Size(m)
}
func (m *Stat) XXX_DiscardUnknown() {
	xxx_messageInfo_Stat.DiscardUnknown(m)
}

var xxx_messageInfo_Stat proto.InternalMessageInfo

func (m *Stat) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Stat) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *Stat) GetType() MetricType {
	if m != nil {
		return m.Type
	}
	return MetricType_CPU_MILLIS
}

func (m *Stat) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type StatRequest struct {
	Partition            string   `protobuf:"bytes,1,opt,name=partition,proto3" json:"partition,omitempty"`
	Stat                 []*Stat  `protobuf:"bytes,2,rep,name=stat,proto3" json:"stat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatRequest) Reset()         { *m = StatRequest{} }
func (m *StatRequest) String() string { return proto.CompactTextString(m) }
func (*StatRequest) ProtoMessage()    {}
func (*StatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a95933fe5266f40f, []int{5}
}

func (m *StatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatRequest.Unmarshal(m, b)
}
func (m *StatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatRequest.Marshal(b, m, deterministic)
}
func (m *StatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatRequest.Merge(m, src)
}
func (m *StatRequest) XXX_Size() int {
	return xxx_messageInfo_StatRequest.Size(m)
}
func (m *StatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatRequest proto.InternalMessageInfo

func (m *StatRequest) GetPartition() string {
	if m != nil {
		return m.Partition
	}
	return ""
}

func (m *StatRequest) GetStat() []*Stat {
	if m != nil {
		return m.Stat
	}
	return nil
}

type HorizontalRecommendationRequest struct {
	Partition            string   `protobuf:"bytes,1,opt,name=partition,proto3" json:"partition,omitempty"`
	Time                 int64    `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HorizontalRecommendationRequest) Reset()         { *m = HorizontalRecommendationRequest{} }
func (m *HorizontalRecommendationRequest) String() string { return proto.CompactTextString(m) }
func (*HorizontalRecommendationRequest) ProtoMessage()    {}
func (*HorizontalRecommendationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a95933fe5266f40f, []int{6}
}

func (m *HorizontalRecommendationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HorizontalRecommendationRequest.Unmarshal(m, b)
}
func (m *HorizontalRecommendationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HorizontalRecommendationRequest.Marshal(b, m, deterministic)
}
func (m *HorizontalRecommendationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HorizontalRecommendationRequest.Merge(m, src)
}
func (m *HorizontalRecommendationRequest) XXX_Size() int {
	return xxx_messageInfo_HorizontalRecommendationRequest.Size(m)
}
func (m *HorizontalRecommendationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HorizontalRecommendationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HorizontalRecommendationRequest proto.InternalMessageInfo

func (m *HorizontalRecommendationRequest) GetPartition() string {
	if m != nil {
		return m.Partition
	}
	return ""
}

func (m *HorizontalRecommendationRequest) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type HorizontalRecommendationResponse struct {
	Rec                  int32    `protobuf:"varint,1,opt,name=rec,proto3" json:"rec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HorizontalRecommendationResponse) Reset()         { *m = HorizontalRecommendationResponse{} }
func (m *HorizontalRecommendationResponse) String() string { return proto.CompactTextString(m) }
func (*HorizontalRecommendationResponse) ProtoMessage()    {}
func (*HorizontalRecommendationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a95933fe5266f40f, []int{7}
}

func (m *HorizontalRecommendationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HorizontalRecommendationResponse.Unmarshal(m, b)
}
func (m *HorizontalRecommendationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HorizontalRecommendationResponse.Marshal(b, m, deterministic)
}
func (m *HorizontalRecommendationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HorizontalRecommendationResponse.Merge(m, src)
}
func (m *HorizontalRecommendationResponse) XXX_Size() int {
	return xxx_messageInfo_HorizontalRecommendationResponse.Size(m)
}
func (m *HorizontalRecommendationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HorizontalRecommendationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HorizontalRecommendationResponse proto.InternalMessageInfo

func (m *HorizontalRecommendationResponse) GetRec() int32 {
	if m != nil {
		return m.Rec
	}
	return 0
}

type VerticalRecommendationRequest struct {
	Partition            string   `protobuf:"bytes,1,opt,name=partition,proto3" json:"partition,omitempty"`
	Time                 int64    `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerticalRecommendationRequest) Reset()         { *m = VerticalRecommendationRequest{} }
func (m *VerticalRecommendationRequest) String() string { return proto.CompactTextString(m) }
func (*VerticalRecommendationRequest) ProtoMessage()    {}
func (*VerticalRecommendationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a95933fe5266f40f, []int{6}
}

func (m *VerticalRecommendationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerticalRecommendationRequest.Unmarshal(m, b)
}
func (m *VerticalRecommendationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerticalRecommendationRequest.Marshal(b, m, deterministic)
}
func (m *VerticalRecommendationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerticalRecommendationRequest.Merge(m, src)
}
func (m *VerticalRecommendationRequest) XXX_Size() int {
	return xxx_messageInfo_VerticalRecommendationRequest.Size(m)
}
func (m *VerticalRecommendationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerticalRecommendationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerticalRecommendationRequest proto.InternalMessageInfo

func (m *VerticalRecommendationRequest) GetPartition() string {
	if m != nil {
		return m.Partition
	}
	return ""
}

func (m *VerticalRecommendationRequest) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type VerticalRecommendationResponse struct {
	Rec                  []*RecommendedPodResources `protobuf:"bytes,2,rep,name=rec,proto3" json:"rec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}
type RecommendedPodResources struct {
	PodName              string   `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	LowerBound           int64    `protobuf:"varint,4,opt,name=lower_bound,proto3" json:"lower_bound,omitempty"`
	UpperBound           int64    `protobuf:"varint,4,opt,name=upper_bound,proto3" json:"upper_bound,omitempty"`
	Target               int64    `protobuf:"varint,4,opt,name=target,proto3" json:"target,omitempty"`
	ResourceName         string   `protobuf:"bytes,2,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerticalRecommendationResponse) Reset()         { *m = VerticalRecommendationResponse{} }
func (m *VerticalRecommendationResponse) String() string { return proto.CompactTextString(m) }
func (*VerticalRecommendationResponse) ProtoMessage()    {}
func (*VerticalRecommendationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a95933fe5266f40f, []int{7}
}

func (m *VerticalRecommendationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerticalRecommendationResponse.Unmarshal(m, b)
}
func (m *VerticalRecommendationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerticalRecommendationResponse.Marshal(b, m, deterministic)
}
func (m *VerticalRecommendationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerticalRecommendationResponse.Merge(m, src)
}
func (m *VerticalRecommendationResponse) XXX_Size() int {
	return xxx_messageInfo_VerticalRecommendationResponse.Size(m)
}
func (m *VerticalRecommendationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerticalRecommendationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerticalRecommendationResponse proto.InternalMessageInfo

func (m *VerticalRecommendationResponse) GetRec() []*RecommendedPodResources {
	if m != nil {
		return m.Rec
	}
	return []*RecommendedPodResources{}
}

func init() {
	proto.RegisterEnum("proto.EventType", EventType_name, EventType_value)
	proto.RegisterEnum("proto.MetricType", MetricType_name, MetricType_value)
	proto.RegisterType((*Empty)(nil), "proto.Empty")
	proto.RegisterType((*Autoscaler)(nil), "proto.Autoscaler")
	proto.RegisterType((*Pod)(nil), "proto.Pod")
	proto.RegisterType((*EventRequest)(nil), "proto.EventRequest")
	proto.RegisterType((*Stat)(nil), "proto.Stat")
	proto.RegisterType((*StatRequest)(nil), "proto.StatRequest")
	proto.RegisterType((*HorizontalRecommendationRequest)(nil), "proto.HorizontalRecommendationRequest")
	proto.RegisterType((*HorizontalRecommendationResponse)(nil), "proto.HorizontalRecommendationResponse")
	proto.RegisterType((*VerticalRecommendationRequest)(nil), "proto.VerticalRecommendationRequest")
	proto.RegisterType((*VerticalRecommendationResponse)(nil), "proto.VerticalRecommendationResponse")
}

func init() { proto.RegisterFile("skplug.proto", fileDescriptor_a95933fe5266f40f) }

var fileDescriptor_a95933fe5266f40f = []byte{
	// 516 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x5d, 0x8f, 0xd2, 0x40,
	0x14, 0xa5, 0x94, 0xb2, 0x72, 0x41, 0xc4, 0x91, 0x87, 0x4a, 0xcc, 0x2e, 0x36, 0x1a, 0x09, 0x0f,
	0x6b, 0xc2, 0xfa, 0xe8, 0x83, 0x2b, 0x3b, 0xc9, 0x6e, 0xc2, 0x22, 0x0e, 0xe5, 0xb9, 0x99, 0x2d,
	0xe3, 0x06, 0x2d, 0x9d, 0xb1, 0x9d, 0x6e, 0xd2, 0xbf, 0xe1, 0xdf, 0xf2, 0x4f, 0x99, 0xf9, 0xa0,
	0x74, 0x13, 0x1f, 0x8c, 0x4f, 0x9c, 0x39, 0xf7, 0xce, 0x9d, 0x73, 0xce, 0xa5, 0xd0, 0xcb, 0x7f,
	0x88, 0xa4, 0xb8, 0x3f, 0x17, 0x19, 0x97, 0x1c, 0x79, 0xfa, 0x27, 0x38, 0x01, 0x0f, 0xef, 0x85,
	0x2c, 0x83, 0x0f, 0x00, 0x97, 0x85, 0xe4, 0x79, 0x4c, 0x13, 0x96, 0x21, 0x04, 0x2d, 0x59, 0x0a,
	0xe6, 0x3b, 0x63, 0x67, 0xd2, 0x21, 0x1a, 0x2b, 0xae, 0xa4, 0xfb, 0xc4, 0x6f, 0x1a, 0x4e, 0xe1,
	0xa0, 0x04, 0x77, 0xc5, 0xb7, 0xaa, 0x94, 0xd2, 0x7d, 0xd5, 0xae, 0x30, 0x1a, 0x82, 0x97, 0x4b,
	0x2a, 0x99, 0xed, 0x37, 0x07, 0xf4, 0x0e, 0x9e, 0x25, 0x34, 0x97, 0x91, 0xcc, 0x68, 0x9a, 0xef,
	0xe4, 0x8e, 0xa7, 0xbe, 0x3b, 0x76, 0x26, 0x2e, 0xe9, 0x2b, 0x3a, 0xac, 0x58, 0x74, 0x06, 0xdd,
	0x58, 0x14, 0x51, 0xc6, 0x7e, 0x16, 0x2c, 0x97, 0x7e, 0x6b, 0xec, 0x4c, 0x3c, 0x02, 0xb1, 0x28,
	0x88, 0x61, 0x82, 0xdf, 0x0e, 0xf4, 0xf0, 0x03, 0x4b, 0xa5, 0x25, 0xd0, 0x2b, 0xe8, 0x08, 0x9a,
	0x49, 0x33, 0xd4, 0x28, 0x39, 0x12, 0xda, 0xd1, 0x6e, 0x6f, 0xd4, 0xb8, 0x44, 0x63, 0xf4, 0xc6,
	0xba, 0x54, 0x0a, 0xfa, 0xb3, 0x81, 0x49, 0xe6, 0x5c, 0x0f, 0x0d, 0x4b, 0xc1, 0xac, 0xef, 0x0b,
	0x00, 0x5a, 0x25, 0xa3, 0x85, 0x74, 0x67, 0xcf, 0x6d, 0xef, 0x31, 0xb2, 0xeb, 0x06, 0xa9, 0xb5,
	0xa1, 0x53, 0x70, 0x05, 0xdf, 0xfa, 0x9e, 0xee, 0x06, 0xdb, 0xbd, 0xe2, 0xdb, 0xeb, 0x06, 0x51,
	0x85, 0xcf, 0x7d, 0xe8, 0xf1, 0xbb, 0xef, 0x2c, 0x96, 0x11, 0x4f, 0x19, 0xff, 0x16, 0x64, 0xd0,
	0x5a, 0x4b, 0x2a, 0x2b, 0x99, 0x4e, 0x4d, 0xe6, 0x4b, 0x78, 0x22, 0xf8, 0x36, 0xd2, 0x09, 0x9b,
	0x30, 0x4f, 0x04, 0xdf, 0x2e, 0x55, 0xc8, 0x6f, 0x1f, 0x39, 0x38, 0xa8, 0xba, 0x65, 0x32, 0xdb,
	0xc5, 0x35, 0x0b, 0x43, 0xf0, 0x1e, 0x68, 0x52, 0x30, 0x1b, 0xa3, 0x39, 0x04, 0x0b, 0xe8, 0xaa,
	0x37, 0xff, 0x2d, 0xbf, 0x33, 0x68, 0xa9, 0x0d, 0xfa, 0xcd, 0xb1, 0x3b, 0xe9, 0xce, 0xba, 0xf6,
	0x25, 0x7d, 0x5f, 0x17, 0x82, 0x4f, 0xd0, 0x5b, 0x2b, 0xef, 0xff, 0xbd, 0x8e, 0xe0, 0x35, 0x3c,
	0xb5, 0x13, 0x72, 0xc1, 0xd3, 0x9c, 0xa1, 0x01, 0xb8, 0x19, 0x8b, 0xf5, 0x65, 0x8f, 0x28, 0x38,
	0x7d, 0x0f, 0x9d, 0x6a, 0x3d, 0x08, 0xa0, 0x3d, 0x27, 0xf8, 0x32, 0xc4, 0x83, 0x86, 0xc2, 0x9b,
	0xd5, 0x95, 0xc2, 0x8e, 0xc2, 0x57, 0x78, 0x81, 0x43, 0x3c, 0x68, 0x4e, 0x3f, 0x02, 0x1c, 0xd3,
	0x40, 0x7d, 0x80, 0xf9, 0x6a, 0x13, 0xdd, 0xde, 0x2c, 0x16, 0x37, 0xeb, 0x41, 0x03, 0x9d, 0xc2,
	0x68, 0xfe, 0x65, 0x39, 0xdf, 0x10, 0x82, 0x97, 0x61, 0x44, 0xf0, 0xd7, 0x0d, 0x5e, 0x87, 0xeb,
	0x43, 0xdd, 0x99, 0xfd, 0x72, 0xa0, 0xbd, 0x4a, 0x8a, 0xfb, 0x5d, 0x8a, 0xa6, 0xe0, 0xe9, 0x97,
	0xd1, 0x8b, 0xfa, 0xdf, 0xc4, 0x9a, 0x1d, 0xf5, 0x0e, 0xa4, 0xfa, 0x96, 0xd0, 0xe4, 0xb0, 0xcc,
	0x7a, 0x4a, 0x7f, 0xed, 0x9c, 0x81, 0xa7, 0x2d, 0x57, 0x53, 0xeb, 0x11, 0x8e, 0x86, 0x8f, 0x49,
	0x93, 0xca, 0x5d, 0x5b, 0x93, 0x17, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xff, 0xdf, 0xe1, 0x91,
	0xd0, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PluginClient is the client API for Plugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PluginClient interface {
	Event(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*Empty, error)
	Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*Empty, error)
	HorizontalRecommendation(ctx context.Context, in *HorizontalRecommendationRequest, opts ...grpc.CallOption) (*HorizontalRecommendationResponse, error)
	VerticalRecommendation(ctx context.Context, in *VerticalRecommendationRequest, opts ...grpc.CallOption) (*VerticalRecommendationResponse, error)
}

type pluginClient struct {
	cc *grpc.ClientConn
}

func NewPluginClient(cc *grpc.ClientConn) PluginClient {
	return &pluginClient{cc}
}

func (c *pluginClient) Event(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.Plugin/Event", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.Plugin/Stat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) HorizontalRecommendation(ctx context.Context, in *HorizontalRecommendationRequest, opts ...grpc.CallOption) (*HorizontalRecommendationResponse, error) {
	out := new(HorizontalRecommendationResponse)
	err := c.cc.Invoke(ctx, "/proto.Plugin/HorizontalRecommendation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) VerticalRecommendation(ctx context.Context, in *VerticalRecommendationRequest, opts ...grpc.CallOption) (*VerticalRecommendationResponse, error) {
	out := new(VerticalRecommendationResponse)
	err := c.cc.Invoke(ctx, "/proto.Plugin/VerticalRecommendation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServer is the server API for Plugin service.
type PluginServer interface {
	Event(context.Context, *EventRequest) (*Empty, error)
	Stat(context.Context, *StatRequest) (*Empty, error)
	HorizontalRecommendation(context.Context, *HorizontalRecommendationRequest) (*HorizontalRecommendationResponse, error)
	VerticalRecommendation(context.Context, *VerticalRecommendationRequest) (*VerticalRecommendationResponse, error)
}

// UnimplementedPluginServer can be embedded to have forward compatible implementations.
type UnimplementedPluginServer struct {
}

func (*UnimplementedPluginServer) Event(ctx context.Context, req *EventRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Event not implemented")
}
func (*UnimplementedPluginServer) Stat(ctx context.Context, req *StatRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stat not implemented")
}
func (*UnimplementedPluginServer) HorizontalRecommendation(ctx context.Context, req *HorizontalRecommendationRequest) (*HorizontalRecommendationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HorizontalRecommendation not implemented")
}

func (*UnimplementedPluginServer) VerticalRecommendation(ctx context.Context, req *VerticalRecommendationRequest) (*VerticalRecommendationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerticalRecommendation not implemented")
}

func RegisterPluginServer(s *grpc.Server, srv PluginServer) {
	s.RegisterService(&_Plugin_serviceDesc, srv)
}

func _Plugin_Event_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Event(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Plugin/Event",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Event(ctx, req.(*EventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Plugin/Stat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Stat(ctx, req.(*StatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_Horizontal_Recommendation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HorizontalRecommendationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).HorizontalRecommendation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Plugin/HorizontalRecommendation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).HorizontalRecommendation(ctx, req.(*HorizontalRecommendationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_Vertical_Recommendation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerticalRecommendationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).VerticalRecommendation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Plugin/VerticalRecommendation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).VerticalRecommendation(ctx, req.(*VerticalRecommendationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Plugin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Plugin",
	HandlerType: (*PluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Event",
			Handler:    _Plugin_Event_Handler,
		},
		{
			MethodName: "Stat",
			Handler:    _Plugin_Stat_Handler,
		},
		{
			MethodName: "HorizontalRecommendation",
			Handler:    _Plugin_Horizontal_Recommendation_Handler,
		},
		{
			MethodName: "VerticalRecommendation",
			Handler:    _Plugin_Vertical_Recommendation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "skplug.proto",
}
