@startuml

title Traffic

skinparam BoxPadding 8
skinparam ParticipantPadding 5

box "Traffic"
    participant RequestGenerator
    participant RequestsArrived
end box

box "KnativeBuffer"
    participant RequestsBuffered
end box

box "Replica"
    participant RequestsProcessing
    participant RequestsFinished
end box

box "Autoscaler"
    participant Calculating
    participant Waiting
end box

== Requests Causing Scale Up From Zero ==

activate Waiting
activate RequestGenerator
    RequestGenerator --> RequestGenerator: create request
    RequestGenerator -> RequestsArrived: <<request>>
activate RequestsArrived
    RequestsArrived -> RequestsBuffered
deactivate RequestsArrived
activate RequestsBuffered
    RequestsBuffered --> Waiting: record stat ("poke")
    Waiting -> Calculating: <<autoscaler>>
deactivate Waiting
activate Calculating
    Calculating --> Calculating: scale up
    note over RequestsProcessing, RequestsFinished
        RequestsProcessing & RequestsFinished
        are actually created simultaneously
        during the scaling process.
    end note
    Calculating -->> RequestsProcessing **
    Calculating -->> RequestsFinished **
    Calculating -> Waiting: <<autoscaler>>
deactivate Calculating
activate Waiting
    RequestsBuffered -> RequestsProcessing: <<request>>
deactivate RequestsBuffered
activate RequestsProcessing
    Waiting -> Calculating: <<autoscaler>>
deactivate Waiting
activate Calculating
    Calculating --> RequestsProcessing: autoscaler calculating
    RequestsProcessing --> Calculating: record stat
    Calculating -> Waiting: <<autoscaler>>
deactivate Calculating
    RequestsProcessing -> RequestsFinished: <<request>>
deactivate RequestsProcessing
activate Waiting
activate RequestsFinished #Orange

== Replicas Active; No Requests Being Processed ==

    Waiting -> Calculating: <<autoscaler>>
deactivate Waiting
activate Calculating
    Calculating --> RequestsProcessing: autoscaler calculating
    RequestsProcessing --> Calculating: record stat

== Replicas Active; Requests Being Processed ==

    Calculating -> Waiting: <<autoscaler>>
deactivate Calculating
activate Waiting
    RequestGenerator --> RequestGenerator: create request
    RequestGenerator -> RequestsArrived: <<request>>
activate RequestsArrived
    RequestsArrived -> RequestsBuffered: <<request>>
deactivate RequestsArrived
activate RequestsBuffered
    RequestsBuffered -> RequestsProcessing: <<request>>
deactivate RequestsBuffered
activate RequestsProcessing
    Waiting -> Calculating: <<autoscaler>>
deactivate Waiting
activate Calculating
    Calculating --> RequestsProcessing: autoscaler calculating
    RequestsProcessing --> Calculating: record stat
    Calculating -> Waiting: <<autoscaler>>
deactivate Calculating
activate Waiting
    RequestsProcessing -> RequestsFinished: <<request>>
deactivate RequestsProcessing
... ...
@enduml

